config/routes.rb
Rails.application.routes.draw do
  get 'users', to: 'users#index'

  devise_for :users
  root to: redirect('/cats')
  resources :cats do
    get 'search', on: :collection
    get 'star', on: :member
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
class Cat < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
  belongs_to :user
  has_one :picture
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :cats
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_cat, only: [:show, :edit, :update, :destroy, :star]

  # GET /cats
  # GET /cats.json
  def index
    @cats = Cat.all
  end

  def search
    @cats = Cat.where("name like '#{params[:term]}%'")
    render action: 'index'
  end

  def star
    @cat.stars = @cat.stars + 1
    @cat.save!
    redirect_to cats_path
  end

  # GET /cats/1
  # GET /cats/1.json
  def show
    view = params.fetch(:details, :show)
    render view
  end

  # GET /cats/new
  def new
    @cat = Cat.new
  end

  # GET /cats/1/edit
  def edit
  end

  # POST /cats
  # POST /cats.json
  def create
    @cat = Cat.new(cat_params)
    @cat.user = User.last

    respond_to do |format|
      if @cat.save
        format.html { redirect_to @cat, notice: 'Cat was successfully created.' }
        format.json { render :show, status: :created, location: @cat }
      else
        format.html { render :new }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cats/1
  # PATCH/PUT /cats/1.json
  def update
    respond_to do |format|
      make_backup @cat.picture.path, params[:cat][:picture].original_filename unless params[:cat][:picture].nil?
      if @cat.update(cat_params)
        format.html { redirect_to @cat, notice: 'Cat was successfully updated.' }
        format.json { render :show, status: :ok, location: @cat }
      else
        format.html { render :edit }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cats/1
  # DELETE /cats/1.json
  def destroy
    @cat.destroy
    respond_to do |format|
      format.html { redirect_to cats_url, notice: 'Cat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def make_backup file_name, orig_name
    data_path = Rails.root.join("public", "data")
    system("mkdir -p #{data_path}")
    system("cp #{file_name} #{data_path}/bak#{Time.zone.now.to_i}_#{orig_name}")
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_cat
    @cat = Cat.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def cat_params
    params.require(:cat).permit(:name, :description, :picture, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    respond_to do |format|
      format.html
      format.json { render json: @users.map{|u| u.attributes}.to_json }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_foot.html.erb
<footer>
  <div class="container">
    Rails Grills <%= Time.now.year %>
  </div>
</footer>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.js"></script>

app/views/application/_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">The Cats Database</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/cats">Cats</a></li>
        <li><a href="/users">Users</a></li>
      </ul>
      <p class="navbar-text pull-right">
        <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
      </p>
      <form action='/cats/search' class='navbar-form navbar-right' style='margin-top: 12px'>
        <input type='search' name='term' valu="<%= params[:term].nil? ? '' : content_tag(params[:term]) %>" />
        <input type='submit' name='search' value='search' />
      </form>
    </div>
  </div>
</nav>

app/views/cats/_form.html.erb
<%= form_for(cat, html: { class: "form form-horizontal" }) do |form| %>
  <% if cat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cat.errors.count, "error") %> prohibited this cat from being saved:</h2>

      <ul>
      <% cat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :cat_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :cat_description %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture, id: :cat_picture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cats/details.html.erb
<p>
  <strong>Name:</strong>
  <%= @cat.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @cat.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@cat.picture_url, width: 600) if @cat.picture.present? %>
</p>

<%= link_to 'Edit', edit_cat_path(@cat) %> |
<%= link_to 'Back', cats_path %>

<button data-toggle="collapse" data-target="<img src=x onerror=alert(0)>">Test</button>

app/views/cats/edit.html.erb
<h1>Editing Cat</h1>

<%= render 'form', cat: @cat %>

<%= link_to 'Show', @cat %> |
<%= link_to 'Back', cats_path %>

app/views/cats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cats</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Picture</th>
      <th>Rating</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @cats.each do |cat| %>
      <tr>
        <td><%= cat.name %></td>
        <td><%= cat.description %></td>
        <td><%= image_tag cat.picture_url(:thumb) if cat.picture.present? %></td>
        <td><%= cat.stars %>x *</td>
        <td><%= link_to 'Give a Star', star_cat_path(cat) %></td>
        <td><%= link_to 'Show', cat %></td>
        <td><%= link_to 'Edit', edit_cat_path(cat) %></td>
        <td><%= link_to 'Destroy', cat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cat', new_cat_path %>

app/views/cats/new.html.erb
<h1>New Cat</h1>

<%= render 'form', cat: @cat %>

<%= link_to 'Back', cats_path %>

app/views/cats/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @cat.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @cat.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@cat.picture_url, width: 600) if @cat.picture.present? %>
</p>

<%= link_to 'Edit', edit_cat_path(@cat) %> |
<%= link_to 'Back', cats_path %>

<button data-toggle="collapse" data-target="<img src=x onerror=alert(0)>">Test</button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cats database</title>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<%= render partial: 'nav' %>
  <div class="container">
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </div>
<%= render partial: 'foot' %>
</body>
</html>

app/views/users/index.html.erb
<h1>List all Users</h1>
<ul>
<% @users.each do |user| %>
<li><%= user.email %>, number of cats: <%= user.cats.size %></li>
<% end %>
</ul>